[browser]
    gatherUsageStats = false
[server]
port = 8501
enableCORS = false

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 400

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 400

# Enables support for websocket compression.
# Default: false
#enableWebsocketCompression = true

[theme]
# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = 'black'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'black'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


